### PR TITLE
Made interval configurable and run forever

### PR DESCRIPTION
**Pull request by KartulUdus**
No reason to put this in crontab. 

this pr will add config option for interval and it will check and restart every "interval"

### CODE REVIEW

**Comment by ColdShadow80** [comment]
Great idea

**Comment by KartulUdus** [comment]
it didn't work as it returned out when it found nothing 😄 

made it better and actually work

**Comment by ColdShadow80** [comment]
Not timestamp seems not to update:

{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }
{ now: 1572524437,
  timeoutAgo: 1572524377,
  response: { empty: true } }

**Comment by KartulUdus** [comment]
you are absolutely right, sorry my oversight. 
pushed a fix

**Comment by darkelement1987** [comment]
Can you put readme changes in the PR as well :D ?

**Comment by heinbakker** [comment]
The current version is working but has some bugs.
It is missing some shiny encounters and I receive double or triple notifications of the the same shiny.

**Comment by na-ji** [comment]
Nice, thank you @KartulUdus. I did not want to bother with memory management, this is why I made it run with a cron. But since it's a popular change, I will merge it.
@heinbakker This bug is because of the query Madmin run, which is based on the time of last update instead of first encounter. It is probably because MAD does not now when the IV have been checked, so you would miss some shiny if the query was based on the creation date. :thinking:

**Pull request merged**
